name: Build and Test (rolling)

on:
  # Triggers the workflow on push
  push:
    branches: [ ros2 ]

  # Triggers the workflow on pull requests
  pull_request:
    branches: [ ros2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble

    steps:
      - uses: ros-tooling/setup-ros@master
        with:
          use-ros2-testing: true
      - uses: ros-tooling/action-ros-ci@master
        with:
          target-ros2-distro: rolling
